### ISSUE TITLE
Allow router to be initialised with a complete stack, for rehydration

### ISSUE THREAD

**Issue by christianchown** [sergeyshpadyrev/react-native-easy-router#12]
Hi @sergeyshpadyrev, would it be possible for a router to be initialised with a complete stack? Maybe `initialRoute` could take an array?

```
<EasyRouter
  initialRoute={[
    {
      id: 'screen1',
      route: 'Screen1',
      params: {},
      animation: { type: 'none' }
    },
    {
      id: 'screen2',
      route: 'Screen2',
      params: { lol: 'wut' },
      animation: { type: 'fade', duration: 900 }
    },
    {
      id: 'screen3',
      route: 'Screen2',
      params: { foo: 'bar' },
      animation: { type: 'left', duration: 700 }
    }
  ]}
/>
```
This means I can store an exact navigation state via `onStackChange`, and then rehydrate it when my app restarts.

It could be (crudely) done at the moment by pushing all the screens with `animation: {type: 'none'}`, but then any `.pop()`s won't have the correct animation.

**Comment by christianchown** [comment]
@sergeyshpadyrev brilliant stuff 😃

**Comment by sergeyshpadyrev** [comment]
So it's done in v3
