### ISSUE TITLE
Change examples from expo to bare react native

### ISSUE THREAD

**Issue by sergeyshpadyrev** [sergeyshpadyrev/react-native-easy-router#17]

**Comment by christianchown** [comment]
Could do both? 

- Have expo/non-expo directories, or 
- (like I did on my [easyrouter](https://github.com/christianchown/easyrouter) demo) Have a separate branch

Although that makes a problem with having duplicated src files, or of managing branches

**Comment by sergeyshpadyrev** [comment]
I think we don't need expo at examples. We don't use it
