### ISSUE TITLE
Fade transition does not remove fade out old (/first) screen?

### ISSUE THREAD

**Issue by jliebrand** [sergeyshpadyrev/react-native-easy-router#27]
If I have two screens, and push from screenA to screenB with a fade animation, then the screenA does not fade out.

If my screenB is (semi) transparent, this becomes problematic

**Comment by christianchown** [comment]
Ah yes. This behaviour is deliberate, because for a standard cross-fade the background must stay opaque, and just foreground must fade, otherwise you will get a flash 

- consider a red pixel (255, 0, 0, 1) on screenA and screenB
- if they both fade, at half way point of tranisition you will get (255, 0, 0, 0.5) + (255, 0, 0, 0.5) = (255, 0, 0, 0.75)

I'll have a think on how best to do this properly, but this may also work:

```
const animations = { 
  fadeboth : [
    { opacity: 0, transform: [{}] }, 
    { opacity: 1, transform: [{}] },
    true,
  ],
};
<Router animations={animations} {...routerProps} />

...

router.push.ScreenB({}, { type: 'fadeboth' })
```
The reason this may work is that the router will see a `transform` (even though it is empty) and will (hopefully!) think it is safe to fade out screenA

**Comment by jliebrand** [comment]
Ah ok... so just so I understand, that workaround it really should be called "fadeIn" right? eg the animation is just for the new screen, and the router auto-fades the old screen?

It would be nice if it would be possible to provide both the animation for the screen that is leaving as well as the one that is entering. In general, if you want to achieve nice motion it's good to have the in vs out transitions be different (here's a good article on why: https://uxdesign.cc/the-ultimate-guide-to-proper-use-of-animation-in-ux-10bd98614fa9)

**Comment by jliebrand** [comment]
Or alternatively, as per the stated design, not have the router do any animation, but leave that up to the client. Eg let the router provide hooks to allow you to do it (Animated value or something), but let the UX decide what it looks like

**Comment by christianchown** [comment]
> Ah ok... so just so I understand, that workaround it really should be called "fadeIn" right? eg the animation is just for the new screen, and the router auto-fades the old screen?

Yes, the router auto-fades the old screen. The decision on [whether to do so is here](https://github.com/sergeyshpadyrev/react-native-easy-router/blob/c9a7600a96d7d977c9e3c02308093f8a897380bf/src/animation.js#L47-L50)

> Or alternatively, as per the stated design, not have the router do any animation, but leave that up to the client. Eg let the router provide hooks to allow you to do it (Animated value or something), but let the UX decide what it looks like

I like the idea of this. It would be nice to move animations out of the core router, and just plugin the existing ones as a default set somehow. Do you have any ideas on what the API might look like?

**Comment by sergeyshpadyrev** [comment]
@christianchown I found that this fading in/out causes troubles when you use animation type "none".
If you move from First screen to Second with "none" animation then from Second to Third with some other animation and do pop twice you see white screen

**Comment by jliebrand** [comment]
Sorry I didn't reply @christianchown ... Having given this all of 5 min to think about (:-)), I suspect the router will still need to be involved a little, as it will need to ensure the current vs next elements are kept in the tree long enough for the animation to make sense.

So I wouldn't think it requires a lot of change. Right now the api is:

push(params, anims)

I would keep that, but just remove the default transitions. Eg it's up to the client to pass animations (or not).

Also: it might be good to allow the client to provide anims for both then new screen, but also optionally the old one. That will allow you to transition the old one off the screen in a different way optionally.

push(params, newScreenAnims, optOldScreenAnims)

And finally, the <Router> itself should allow you to pass in "initialAnim" along side "initalRoute", to set the initial animations.

If that's not passed (or if no anims are passed in the push/replace/etc), then just dont animate anything
