### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by epoxa** [sergeyshpadyrev/react-native-easy-router#35]
I got two warnings after installing Navigator:
1) compnentWillReceiveProps is deprecated (in withAnimatable(View))
2) componentWillMount is deprecated (in Navigator by its own)
Any suggestions or upcoming updates? Thanks

**Comment by sergeyshpadyrev** [comment]
I will look what I can do

**Comment by sergeyshpadyrev** [comment]
Done and released in v3.1.0
