### ISSUE TITLE
How to update current screen when props are changes ???.....How to make forceUpdate?

### ISSUE THREAD

**Issue by Azarians** [sergeyshpadyrev/react-native-easy-router#42]

**Comment by sergeyshpadyrev** [comment]
Any screen is just a React Component. You can do with it anything you can do with any other React Component

**Comment by Azarians** [comment]
Thanks for the quick reply ))....I need to rerender first screen ( initial stack), when component props ( where is located navigator) changes, how I can do it?

**Comment by sergeyshpadyrev** [comment]
I think it's not possible because screens are generated once in the very beginning from initial stack and then you can work with them. But what do you need to do? Maybe there's a better way to solve your problem.
