### ISSUE TITLE
Router can be unmounted during a transition, causing a no-op

### ISSUE THREAD

**Issue by christianchown** [sergeyshpadyrev/react-native-easy-router#9]
If you unmount your router component before a transition has completed, you get:

 > Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Router component.

This comes from the `setState()`s that occur after async promise resolutions in `pop`, `replace`, `reset` and `addScreen`.

I suggest replacing these with an `_isMounted` guard or similar from: https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html

**Comment by sergeyshpadyrev** [comment]
Fixed by @christianchown
